import React, { useEffect } from 'react';
import Header from '../Header';
import Footer from '../Footer';
import VideoLogo from '../VideoLogo';
import OptimizedParticles from '../OptimizedParticles';
import { useMobileOptimizations } from '../../hooks/useMobileOptimizations';
import './PrivacyPolicy.css';

const PrivacyPolicy = () => {
  const { particleConfig, blurConfig, networkOptimizations } = useMobileOptimizations('privacy');

  useEffect(() => {
    document.title = 'Privacy Policy - Kalakritam | Hyderabad';
    const metaDescription = document.querySelector('meta[name="description"]');
    const content = 'Read the Privacy Policy for Kalakritam (Hyderabad). Learn how we collect, use, and protect your personal data when you use our website and services.';
    if (metaDescription) {
      metaDescription.setAttribute('content', content);
    } else {
      const meta = document.createElement('meta');
      meta.name = 'description';
      meta.content = content;
      document.head.appendChild(meta);
    }
  }, []);

  return (
    <div className="policy-container" data-connection={networkOptimizations.lowerQuality ? 'slow' : 'fast'}>
      {/* Particles Background - Optimized for mobile */}
      <OptimizedParticles
        particleConfig={particleConfig}
        networkOptimizations={networkOptimizations}
        className="policy-particles-background"
      />

      {/* Blur Overlay */}
      <div
        className="policy-blur-overlay"
        style={{ backdropFilter: blurConfig.backdropFilter, background: blurConfig.background }}
      />

      <VideoLogo />
      <Header currentPage="privacy" />

      <main className="policy-content" role="main">
        <section className="policy-hero">
          <h1 className="policy-title">Privacy Policy</h1>
          <p className="policy-updated">Last updated: October 22, 2025</p>
        </section>

        <section className="policy-body">
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
          </p>

          <h2>Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>
            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to kalakritam, Hyderabad.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: Telangana, India</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>Website</strong> refers to Kalakritam, accessible from <a href="https://kalakritam.in/" target="_blank" rel="noopener noreferrer">https://kalakritam.in/</a></li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2>Collecting and Using Your Personal Data</h2>
          <h3 id="google-oauth">Google OAuth 2.0 Authentication</h3>
          <p>
            Kalakritam uses <strong>Google OAuth 2.0</strong> as an authentication method to allow users to sign in securely using their Google account. When you choose to sign in with Google, we request access to the following information from your Google account:
          </p>
          <ul>
            <li><strong>Email address:</strong> Used to identify your account and send workshop registration confirmations, event notifications, and important updates</li>
            <li><strong>Name (First and Last):</strong> Used to personalize your experience and for workshop registration purposes</li>
            <li><strong>Profile Picture:</strong> Optionally displayed in your user profile within the Kalakritam platform</li>
            <li><strong>Google User ID:</strong> A unique identifier used to link your Google account to your Kalakritam account</li>
          </ul>
          <p>
            <strong>Important:</strong> We never access your Google password, and we do not request access to any other Google services (Gmail, Drive, Calendar, etc.). 
            You can revoke Kalakritam's access to your Google account at any time by visiting your{' '}
            <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener noreferrer">Google Account Permissions</a>.
          </p>
          <p>
            Kalakritam's use of information received from Google APIs adheres to the{' '}
            <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noopener noreferrer">
              Google API Services User Data Policy
            </a>, including the Limited Use requirements.
          </p>

          <h3>Types of Data Collected</h3>
          <h4>Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul>
            <li>Email address (via Google OAuth or direct registration)</li>
            <li>First name and last name</li>
            <li>Phone number (for workshop bookings)</li>
            <li>Address, State, Province, ZIP/Postal code, City (if provided for event registration)</li>
            <li>Profile picture (via Google OAuth)</li>
            <li>Usage Data</li>
          </ul>

          <h4>Usage Data</h4>
          <p>
            Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>

          <h3>Tracking Technologies and Cookies</h3>
          <p>
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
          </p>
          <p>
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
          </p>
          <h4>We use both Session and Persistent Cookies for the purposes set out below:</h4>
          <ul>
            <li><strong>Necessary / Essential Cookies</strong> (Session, administered by Us): Essential to provide services and prevent fraudulent use of user accounts.</li>
            <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> (Persistent, administered by Us): Identify if users have accepted the use of cookies.</li>
            <li><strong>Functionality Cookies</strong> (Persistent, administered by Us): Remember choices You make to provide a more personal experience.</li>
          </ul>

          <h2>Use of Your Personal Data</h2>
          <p>The Company may use Personal Data (including information obtained via Google OAuth) for the following purposes:</p>
          <ul>
            <li><strong>Account Authentication:</strong> To verify your identity and provide secure access to your account via Google OAuth.</li>
            <li><strong>Workshop Registration:</strong> To register you for art workshops and send confirmation emails.</li>
            <li><strong>Event Notifications:</strong> To notify you about upcoming workshops, events, and cultural programs.</li>
            <li><strong>Personalized Experience:</strong> To customize your dashboard and display your workshop history.</li>
            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
            <li>To manage Your Account as a user of the Service.</li>
            <li>For the performance of a contract for products, items or services (workshop bookings, event tickets).</li>
            <li>To contact You regarding updates or informative communications related to workshops and events.</li>
            <li>To provide You with news, special offers, and general information about art workshops, services and events.</li>
            <li>To manage Your requests to Us.</li>
            <li>For business transfers such as mergers or acquisitions.</li>
            <li>For other purposes like data analysis, usage trends, and improving our Service.</li>
          </ul>
          <p>
            <strong>Data from Google OAuth:</strong> Information obtained through Google OAuth (email, name, profile picture) is used solely for the purposes 
            listed above and is never sold, rented, or shared with third parties for marketing purposes. We comply with Google's API Services User Data Policy, 
            including the Limited Use requirements.
          </p>

          <h3>Sharing Your Personal Information</h3>
          <ul>
            <li>With Service Providers to monitor and analyze the use of our Service, to contact You.</li>
            <li>For business transfers including negotiations.</li>
            <li>With Affiliates under this Privacy Policy.</li>
            <li>With business partners to offer certain products, services or promotions.</li>
            <li>With other users in public areas of the Service.</li>
            <li>With Your consent.</li>
          </ul>

          <h2>Retention of Your Personal Data</h2>
          <p>
            We will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy and as required to comply with legal obligations, resolve disputes, and enforce agreements.
          </p>

          <h2>Transfer of Your Personal Data</h2>
          <p>
            Your information may be transferred to — and maintained on — computers located outside of Your jurisdiction where data protection laws may differ. We will take reasonable steps to ensure Your data is treated securely.
          </p>

          <h2>Delete Your Personal Data</h2>
          <p>
            You have the right to delete or request that We assist in deleting Personal Data We have collected about You. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
          </p>

          <h2>Disclosure of Your Personal Data</h2>
          <h3>Business Transactions</h3>
          <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.</p>
          <h3>Law enforcement</h3>
          <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law.</p>
          <h3>Other legal requirements</h3>
          <ul>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>

          <h2>Security of Your Personal Data</h2>
          <p>
            While We strive to use commercially reasonable means to protect Your Personal Data, no method of transmission over the Internet or method of electronic storage is 100% secure.
          </p>

          <h2>Children's Privacy</h2>
          <p>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
          </p>

          <h2>Links to Other Websites</h2>
          <p>
            Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>

          <h2>Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
          </p>

          <h2>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul>
            <li>By email: <a href="mailto:contact@kalakritam.in">contact@kalakritam.in</a></li>
            <li>By visiting this page on our website: <a href="https://kalakritam.in/contact" target="_blank" rel="noopener noreferrer">https://kalakritam.in/contact</a></li>
            <li>By phone: <a href="tel:+917032201999">7032201999</a></li>
          </ul>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
